domain: nskernel.github.io
url: https://nskernel.github.io
baseurl: /
production_url : https://nskernel.github.io
repository: NSKernel/personal-site
title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
