domain: nskernel.github.io
url: https://nskernel.github.io
baseurl: /
production_url : https://nskernel.github.io
repository: NSKernel/nskernel.github.io
title: Shixuan Zhao's Homepage
logo: /assets/img/logo.png
description: This is Shixuan Zhao's homepage
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal